# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-15 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20170415_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.CharField(default='', max_length=5),
        ),
    ]
