# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20170415_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_type',
            field=models.CharField(choices=[('Prescription', 'Prescription'), ('Bloodwork', 'Bloodwork'), ('Allergy', 'Allergy'), ('CT', 'Cat Scan'), ('Additional Notes', 'Additional Notes')], default='Additional Notes', max_length=30),
        ),
    ]
